name: Deploy Chatbot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List directory structure
      run: ls -R

    - name: Ensure src directory exists
      run: mkdir -p ./src

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      # 'working-directory'를 생략하거나 올바른 디렉토리 설정을 추가할 수 있습니다.
      # working-directory: ./  # 루트 디렉토리에서 실행 (기본 설정)

    - name: Build the project
      run: npm run build
      # 'working-directory'를 생략하거나 올바른 디렉토리 설정을 추가할 수 있습니다.
      # working-directory: ./  # 루트 디렉토리에서 실행 (기본 설정)

    - name: Inject API Key
      run: |
        echo "export const apiKey = '${{ secrets.OPENAI_API_KEY }}';" > ./src/apiKey.js
      shell: bash
      # 'working-directory'를 생략하거나 올바른 디렉토리 설정을 추가할 수 있습니다.
      # working-directory: ./  # 루트 디렉토리에서 실행 (기본 설정)

    - name: Deploy
      run: npm run deploy
      # 'working-directory'를 생략하거나 올바른 디렉토리 설정을 추가할 수 있습니다.
      # working-directory: ./  # 루트 디렉토리에서 실행 (기본 설정)
