name: Deploy Chatbot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List directory structure
      run: ls -R

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./  # package.json이 루트 디렉토리에 있는 경우

    - name: Build the project
      run: npm run build
      working-directory: ./  # package.json이 루트 디렉토리에 있는 경우

    - name: Inject API Key
      run: |
        echo "export const apiKey = '${{ secrets.OPENAI_API_KEY }}';" > ./src/apiKey.js
      shell: bash
      working-directory: ./  # package.json이 루트 디렉토리에 있는 경우

    - name: Deploy
      run: npm run deploy
      working-directory: ./  # package.json이 루트 디렉토리에 있는 경우
